name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: ehkcontainer.azurecr.io
           username: ehkContainer
           password: XoAmr5iYf2L4eag+ZS70li5ZFSqxAJrCR7C+8T04Uf+ACRBBrf7I
      - run: |
          docker build . -t ehkcontainer.azurecr.io/knowledgefactory:${{ github.sha }}
          docker push ehkcontainer.azurecr.io/knowledgefactory:${{ github.sha }}
